version: "2.0"
services:
  web:
    image: ghcr.io/ovrclk/chain-supply:v0.0.1
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
        accept:
          - supply.akash.pub

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    ewr:
      attributes:
        host: akash
        datacenter: equinix-metal-ewr1
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    ewr:
      profile: web
      count: 1
