name: publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "~1.24"
      - name: build
        run: |
          go build .
      - name: release
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/${{github.repository}}:${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{github.repository}}:${GITHUB_REF#refs/tags/} ghcr.io/${{github.repository}}:latest
          docker push ghcr.io/${{github.repository}}:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{github.repository}}:latest
